dist: trusty
language: c

install:
    # compile and install cmocka test framework
    - cd /tmp
    - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar -xvf cmocka-1.1.0.tar.xz
    - cd cmocka-1.1.0
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/tmp/cmocka ..
    - make install
    - export LD_LIBRARY_PATH="/tmp/cmocka/lib:$LD_LIBRARY_PATH"

before_script:
    # make sure we end up in the project repository before building
    - cd $TRAVIS_BUILD_DIR

script:
    - make DEBUG=1 NOWIRINGPI=1 test
    - ./test/run_unit_tests.sh

after_success:
    - gcov -bclp lib/*.c bin/*.c
    - bash <(curl -s https://codecov.io/bash)
