before_install:
    # update package list
    - sudo apt-get -qq update

install:
    # install address sanitizer
    - sudo apt-get install -y libasan2
    # compile and install cmocka test framework
    - cd /tmp
    - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar -xvf cmocka-1.1.0.tar.xz
    - cd cmocka-1.1.0
    - mkdir build
    - cd build
    - cmake ..
    - sudo make install
    - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

before_script:
    # make sure we end up in the project repository before building
    - cd $TRAVIS_BUILD_DIR

script:
    - make DEBUG=1
    - ./test/test_response_parser
    - ./test/test_settings_parser

language: c
